#!/usr/bin/env python

import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

import logging
import sys, time
from daemon import Daemon
import run_thread as thread


class MyDaemon(Daemon):
    def run(self):
        while True:
            logging.getLogger().setLevel(logging.INFO)
            retry_sec = 10
            try:
                logging.info("Thread starting ...")
                while True:
                    thread.main()
            except Exception, msg:
                logging.exception(msg)
                logging.warn("Restarting the thread in %s seconds" % retry_sec)
            time.sleep(retry_sec)


if __name__ == "__main__":
    daemon = MyDaemon('/tmp/daemon-example.pid', stderr='/dev/shm/stderr')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
